import os
import datetime
import re
from pathlib import Path

def get_weekly_summary():
    log_dir = os.environ.get("LOG_DIR", "logs")
    summary_dir = os.environ.get("SUMMARY_DIR", "summaries")
    os.makedirs(summary_dir, exist_ok=True)
    
    today = datetime.date.today()
    last_7_days = [today - datetime.timedelta(days=i) for i in range(7)]
    
    combined_topics = []
    total_code_entries = 0
    problems_resolved = 0
    total_logs_found = 0
    
    highlights = []

    for date in sorted(last_7_days):
        log_file = Path(log_dir) / f"{date.strftime('%Y-%m-%d')}.md"
        if log_file.exists():
            total_logs_found += 1
            content = log_file.read_text(encoding="utf-8")
            
            # Extract Learning Topics
            topics = re.findall(r"## 🧠 Learning & Discovery\n(.*?)\n##", content, re.DOTALL)
            if topics:
                items = [t.strip("- [ ] ").strip() for t in topics[0].split("\n") if t.strip("- [ ] ").strip() and "*" not in t]
                combined_topics.extend(items)
            
            # Extract Code Written count
            code_sections = re.findall(r"## 💻 Code & Implementation\n(.*?)\n##", content, re.DOTALL)
            if code_sections:
                items = [c for c in code_sections[0].split("\n") if c.strip("- [ ] ").strip() and "*" not in c]
                total_code_entries += len(items)
                
            # Problems Faced vs Solutions
            solutions = re.findall(r"## ✅ Solutions & Breakthroughs\n(.*?)\n##", content, re.DOTALL)
            if solutions and solutions[0].strip() and "*" not in solutions[0]:
                items = [s for s in solutions[0].split("\n") if s.strip("- [ ] ").strip() and "*" not in s]
                problems_resolved += len(items)

            highlights.append(f"### {date.strftime('%A, %b %d')}\n- 📝 Daily log entry processed.")

    summary_path = Path(summary_dir) / "weekly-summary.md"
    
    unique_topics = sorted(list(set(combined_topics)))
    productivity_score = (total_logs_found / 7) * 100
    
    summary_content = f"""# 📊 Weekly Developer Summary
> **Period:** { (today - datetime.timedelta(days=6)).strftime('%b %d') } - { today.strftime('%b %d, %Y') }
53: 
54: ---
55: 
56: ## 📈 Productivity Overview
57: | Metric | Value |
58: | :--- | :--- |
59: | **Active Days** | {total_logs_found}/7 |
60: | **Productivity Score** | {productivity_score:.1f}% |
61: | **Code Updates** | {total_code_entries} |
62: | **Challenges Solved** | {problems_resolved} |
63: 
64: ---
65: 
66: ## 🧠 Knowledge Gained
67: {chr(10).join([f"- {t}" for t in unique_topics]) if unique_topics else "*No specific topics logged this week.*"}
68: 
69: ## 🚀 Week Highlights
70: {chr(10).join(highlights) if highlights else "*No logs found for the last 7 days.*"}
71: 
72: ## 📅 Looking Ahead
73: - [ ] Maintain consistency in logging
74: - [ ] Deepen focus on key skills
75: 
76: ---
77: <p align="center">
78:   <i>Generated by <b>Daily Dev Log Automation System</b></i>
79: </p>
80: """

    with open(summary_path, "w", encoding="utf-8") as f:
        f.write(summary_content)
    print(f"Weekly summary generated at: {summary_path}")

if __name__ == "__main__":
    get_weekly_summary()
