import os
import datetime
import re
from pathlib import Path

def get_weekly_summary():
    log_dir = os.environ.get("LOG_DIR", "logs")
    summary_dir = os.environ.get("SUMMARY_DIR", "summaries")
    os.makedirs(summary_dir, exist_ok=True)
    
    today = datetime.date.today()
    last_7_days = [today - datetime.timedelta(days=i) for i in range(7)]
    
    combined_topics = []
    total_code_entries = 0
    problems_resolved = 0
    total_logs_found = 0
    
    highlights = []

    for date in sorted(last_7_days):
        log_file = Path(log_dir) / f"{date.strftime('%Y-%m-%d')}.md"
        if log_file.exists():
            total_logs_found += 1
            content = log_file.read_text(encoding="utf-8")
            
            # Extract Learning Topics
            topics = re.findall(r"## Learning Topic\n(.*?)\n##", content, re.DOTALL)
            if topics:
                items = [t.strip("- ").strip() for t in topics[0].split("\n") if t.strip("- ").strip()]
                combined_topics.extend(items)
            
            # Extract Code Written count (simple heuristic: number of list items)
            code_sections = re.findall(r"## Code Written\n(.*?)\n##", content, re.DOTALL)
            if code_sections:
                items = [c for c in code_sections[0].split("\n") if c.strip("- ").strip()]
                total_code_entries += len(items)
                
            # Problems Faced vs Solutions
            problems = re.findall(r"## Problems Faced\n(.*?)\n##", content, re.DOTALL)
            solutions = re.findall(r"## Solutions\n(.*?)\n##", content, re.DOTALL)
            if solutions and solutions[0].strip() and solutions[0].strip() != "-":
                problems_resolved += len([s for s in solutions[0].split("\n") if s.strip("- ").strip()])

            highlights.append(f"### {date.strftime('%A, %b %d %Y')}\n- Processed daily log entry.")

    summary_path = Path(summary_dir) / "weekly-summary.md"
    
    unique_topics = sorted(list(set(combined_topics)))
    productivity_score = (total_logs_found / 7) * 100
    
    summary_content = f"""# Weekly Developer Summary
Generated on: {datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## 📊 Quick Stats
- **Active Days:** {total_logs_found}/7
- **Productivity Score:** {productivity_score:.1f}%
- **Code Modules Updated:** {total_code_entries}
- **Challenges Overcome:** {problems_resolved}

## 🧠 Skills Acquired & Topics Covered
{chr(10).join([f"- {t}" for t in unique_topics]) if unique_topics else "- No specific topics logged."}

## 🚀 Key Highlights
{chr(10).join(highlights) if highlights else "- No logs found for the last 7 days."}

## 📅 Next Week's Outlook
- Continue consistent logging.
- Focus on deepening knowledge in covered topics.

---
*Summary generated by Daily Dev Log Automation System*
"""

    with open(summary_path, "w", encoding="utf-8") as f:
        f.write(summary_content)
    print(f"Weekly summary generated at: {summary_path}")

if __name__ == "__main__":
    get_weekly_summary()
